/**
 * Templates nativos/padrão do sistema — 6 certificados de Consagração.
 * São auto-semeados para cada ministério na primeira vez que acessar a página de certificados.
 * A imagem de fundo é referenciada como caminho público (/img/...) para não inflar o banco com base64.
 */

export type CertificadoCategoria =
  | 'ministerial'
  | 'consagracao-obreiro'
  | 'apresentacao-criancas'
  | 'batismo-aguas'
  | 'ebd'
  | 'casamento';

export const CERTIFICADOS_TEMPLATES_PADRAO = [
  {
    id: 'ministerial-pastor-padrao',
    nome: 'Consagração Pastor(a)',
    chave: 'ministerial-pastor-padrao',
    categoria: 'ministerial' as CertificadoCategoria,
    ativo: true,
    backgroundUrl: '/img/certificado_pastor.jpg',
    orientacao: 'landscape' as const,
    elementos: [
      {
        id: 'd72efd08-445f-4778-aa63-cbc3e8a617b5',
        tipo: 'logo' as const,
        x: 61,
        y: 185,
        largura: 90,
        altura: 90,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '0437f23f-6dfd-4c00-8657-e2515c61b37b',
        tipo: 'texto' as const,
        x: 192,
        y: 222,
        largura: 454,
        altura: 41,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: 'e7d5f046-21f2-4556-bec9-0a65cc0936dd',
        tipo: 'texto' as const,
        x: 217,
        y: 510,
        largura: 199,
        altura: 22,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'right' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '177705368462948dhz32',
        tipo: 'texto' as const,
        x: 421,
        y: 511,
        largura: 199,
        altura: 22,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'left' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'ministerial-evangelista-padrao',
    nome: 'Consagração Evangelista',
    chave: 'ministerial-evangelista-padrao',
    categoria: 'ministerial' as CertificadoCategoria,
    ativo: true,
    backgroundUrl: '/img/certificado_evangelista.jpg',
    orientacao: 'landscape' as const,
    elementos: [
      {
        id: 'ea7378a8-958b-43d3-afdb-b382080cfedc',
        tipo: 'logo' as const,
        x: 54,
        y: 224,
        largura: 94,
        altura: 116,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '8f382add-8fcb-4bcf-9dd3-524e74caa5a4',
        tipo: 'texto' as const,
        x: 196,
        y: 210,
        largura: 440,
        altura: 41,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: '161d7f6b-1f34-42ed-8508-3a48ffd84cd6',
        tipo: 'texto' as const,
        x: 209,
        y: 512,
        largura: 205,
        altura: 23,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777052623192saa853y',
        tipo: 'texto' as const,
        x: 426,
        y: 511,
        largura: 205,
        altura: 23,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'ministerial-missionario-padrao',
    nome: 'Consagração Missionário(a)',
    chave: 'ministerial-missionario-padrao',
    categoria: 'ministerial' as CertificadoCategoria,
    ativo: true,
    backgroundUrl: '/img/certificado_missionario.jpg',
    orientacao: 'landscape' as const,
    elementos: [
      {
        id: 'b9268db5-9e61-48fc-ae7e-9f016afb0e23',
        tipo: 'logo' as const,
        x: 37,
        y: 232,
        largura: 118,
        altura: 132,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '081d551b-d679-4a88-bc34-f931f67b43c8',
        tipo: 'texto' as const,
        x: 183,
        y: 213,
        largura: 471,
        altura: 40,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: 'cb4a1e1b-25aa-43e6-98c1-0945fc43216c',
        tipo: 'texto' as const,
        x: 197,
        y: 514,
        largura: 217,
        altura: 20,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777051489877hrt0a3x',
        tipo: 'texto' as const,
        x: 425,
        y: 514,
        largura: 206,
        altura: 20,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'ministerial-presbitero-padrao',
    nome: 'Consagração Presbítero',
    chave: 'ministerial-presbitero-padrao',
    categoria: 'ministerial' as CertificadoCategoria,
    ativo: true,
    backgroundUrl: '/img/certificado_presbitero.jpg',
    orientacao: 'landscape' as const,
    elementos: [
      {
        id: 'e5390d5e-9d43-4ea4-9aa5-25cae1ea19cb',
        tipo: 'logo' as const,
        x: 42,
        y: 304,
        largura: 105,
        altura: 138,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: 'f7090f99-d1e3-43a6-b5c0-4b1a477c00a7',
        tipo: 'texto' as const,
        x: 186,
        y: 221,
        largura: 465,
        altura: 39,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: '564c9a70-af30-4100-8524-2b6e0f0ff8c4',
        tipo: 'texto' as const,
        x: 219,
        y: 500,
        largura: 193,
        altura: 20,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777050303702z30i3ox',
        tipo: 'texto' as const,
        x: 432,
        y: 499,
        largura: 193,
        altura: 20,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'ministerial-diaconiza-padrao',
    nome: 'Consagração Diaconisa',
    chave: 'ministerial-diaconiza-padrao',
    categoria: 'ministerial' as CertificadoCategoria,
    ativo: true,
    backgroundUrl: '/img/certificado_diaconiza.jpg',
    orientacao: 'landscape' as const,
    elementos: [
      {
        id: 'f06e1232-1ebb-45a5-9a95-969b79f72915',
        tipo: 'logo' as const,
        x: 115,
        y: 192,
        largura: 99,
        altura: 125,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '9875d06a-3d97-44d1-b673-bf6890e0c4e2',
        tipo: 'texto' as const,
        x: 200,
        y: 218,
        largura: 456,
        altura: 39,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: '9a743a50-48f1-45de-aeec-14acbb9759fd',
        tipo: 'texto' as const,
        x: 206,
        y: 479,
        largura: 212,
        altura: 24,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Arial',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777048014058ql55s0s',
        tipo: 'texto' as const,
        x: 422,
        y: 479,
        largura: 212,
        altura: 24,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Arial',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'consagracao-obreiro-padrao',
    nome: 'Consagração de Obreiro',
    chave: 'consagracao-obreiro-padrao',
    categoria: 'consagracao-obreiro' as CertificadoCategoria,
    ativo: true,
    backgroundUrl: '/img/certificado_obreiro.jpg',
    orientacao: 'landscape' as const,
    elementos: [
      {
        id: '5b961f06-7202-4df3-8874-11194f198a4c',
        tipo: 'logo' as const,
        x: 57,
        y: 228,
        largura: 114,
        altura: 151,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '1ef3b217-5578-49b8-9700-76ead5167bf7',
        tipo: 'texto' as const,
        x: 179,
        y: 223,
        largura: 482,
        altura: 42,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{obreiro_nome}',
      },
      {
        id: 'f575e61b-8a5a-455a-b7c0-04981221e918',
        tipo: 'texto' as const,
        x: 198,
        y: 515,
        largura: 220,
        altura: 22,
        fontSize: 11,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'right' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777045799219teof90k',
        tipo: 'texto' as const,
        x: 424,
        y: 516,
        largura: 173,
        altura: 20,
        fontSize: 11,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'left' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
];
